name: Auto Tag on Merge to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Create or Increment Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          
          if [ -z "$latest_tag" ]; then
            new_tag="1.0.0"
          else
            # Parse the semver components (assuming format major.minor.patch)
            IFS='.' read -r major minor patch <<< "$latest_tag"
            new_patch=$((patch + 1))
            new_tag="$major.$minor.$new_patch"
          fi
          
          # Create and push the new tag
          git tag "$new_tag"
          git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$new_tag"
